name: "Deployment Setup"
description: "Determine deployment environment and image tag based on git ref type (tag vs branch)"

outputs:
  environment:
    description: "Target environment (dev or prod)"
    value: ${{ steps.env.outputs.environment }}
  image_tag:
    description: "Docker image tag to use"
    value: ${{ steps.env.outputs.image_tag }}
  commit_author:
    description: "Author name for commits"
    value: ${{ steps.env.outputs.commit_author }}
  commit_email:
    description: "Author email for commits"
    value: ${{ steps.env.outputs.commit_email }}

runs:
  using: "composite"
  steps:
    - name: Determine environment and image tag
      id: env
      shell: bash
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
          echo "image_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

          # Get author info from annotated tag
          AUTHOR=$(git tag -l --format='%(taggername)' "${{ github.ref_name }}")
          EMAIL=$(git tag -l --format='%(taggeremail)' "${{ github.ref_name }}")

          # If empty (lightweight tag), fall back to commit author
          if [ -z "$AUTHOR" ]; then
            AUTHOR=$(git log -1 --format='%an' "${{ github.ref_name }}")
            EMAIL=$(git log -1 --format='%ae' "${{ github.ref_name }}")
          fi

          # Clean up email (remove <>)
          EMAIL=$(echo "$EMAIL" | sed 's/[<>]//g')
        else
          echo "environment=dev" >> $GITHUB_OUTPUT
          echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

          # Get commit author info
          AUTHOR=$(git log -1 --format='%an')
          EMAIL=$(git log -1 --format='%ae')
        fi

        echo "commit_author=$AUTHOR" >> $GITHUB_OUTPUT
        echo "commit_email=$EMAIL" >> $GITHUB_OUTPUT
